// Seed data for FlowForge AI — matches Stitch design screens

export const SEED_USERS = [
  { id: 1, name: 'Alex Rivera', email: 'alex@flowforge.ai', role: 'admin', avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaaCmG2X7M0HRj6oIPO8KLBwFd7ZMD-D3U_3Fcxm43AYgiJIGHCMWPIMWC5PptWnPQi3v0uVtn0Q1ELDCof2k6OinM7CfvsVRN16bTHHGOEz3LjYupZEc7hRW4Yn80iXgjL7LgEO88kbTgk4vaHoFeIDX81uAbh07aSIz8cKjMWffYVMebRrSBHNs4FBwPfCP8Ovm1mqaPNGJxVyPTeYI_ECwKSbCv7E48VLQz-XFNK1LBH-zSoMRwg49535Le3yNQv4czlK9SQg', status: 'online' },
  { id: 2, name: 'Sarah Jenkins', email: 'sarah@flowforge.ai', role: 'pm', avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC5J7e8nRAGDBYSmyrxs5l0lrKsEUN6Cf8Sl2x2u35zRN2cHkyQtkvOtG_VOIeoZwTrXaZYXkqHzCzALEiALH2HoPOQUNeEtMATyZF2Mrky2G4Wlyda7HFA9rC2jXUAGI1zZwFd7eR1XIHFWg1dncOZtNsrvL_cB5JhdtcjysD-gneYvq2CzCLsekJQoB0ftbKbWeIKDdeEOJnBq0jhT5ARrlmVvM2DgXSNXhl82oXQpRMpXvFdk36KTOYK8g9f1lXgz7r-Sbpwow', status: 'online' },
  { id: 3, name: 'Marcus Chen', email: 'marcus@flowforge.ai', role: 'developer', avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAjYOb3KV5tS_RTTVmRMfNdm5EyvRJ95yqndFMwhhc9b7McrsbOcj9_i84Un11WWGf34T3CdnBSNQP6A1cIOfoAxHHG8bdEXAupUsj925mSk4ymZIX0cq-yEMAzaDjq1xExfoTurbwdLCPkvGWSgvjPrcv7EgpBK2967NG9guezpTd41GUQGnIE_2WEsT8moYxOFBDwGFf43d77kJzAMRPcKbGgyFvtMongLOwz7q80jvxCqSlpmkaMlxeZuxWY-ow8TCY5PFSfCw', status: 'away' },
  { id: 4, name: 'Elena Jordan', email: 'elena@flowforge.ai', role: 'developer', avatar: null, initials: 'EJ', status: 'offline' },
  { id: 5, name: 'David Park', email: 'david@flowforge.ai', role: 'developer', avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDwtJjCIsbNExuZA2wJN5wIdeIJTr_qlA7Bp4SqY3zuqLYgien9bOnojFQI9HGOtXa0LU8rFRm5b42dhflA8TtZSFVIPyJOhWjdLfZ-7tjAFyWAA69c-fxdFmAOZC4JrwGcZleKS2lVD_PrzP0Ds11RSBs8RAayLWGVaIBO6Qey7yVpQmkfVscK1Dt1lwzmD98eaoJo9vdFHW4UJc36cMyTZuP1Ju869Pbhg4qlu6agpildk3CWuUrBll1Zjk9GrNh5_IJLWZBv7w', status: 'online' },
  { id: 6, name: 'Priya Sharma', email: 'priya@flowforge.ai', role: 'qa', avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGLhFVceEHDbFVSXBSg47HHiAoMOe2CwGfILvBHPUd8pTvBtfq8R7QhIfApnAnzfGo9ku_jhTxTNkzgo0tFQHG6jKJ8sWGhFAguXdHv6sA027lvnQLMe3grn3xL1JQKmBkOwgE_K3qvNFHxXTiperXFaznCsjN9VgkmRzN8w2MsCKOQOp7ig9nt28a5eRv9NHUrcC__SyWXO2O85C5KnAV4GSv8gczLizZtWsBSDcQtk0Ga1qwoZFLbBhk5edekd1A4AeUtKetCQ', status: 'online' },
]

export const SEED_PROJECTS = [
  {
    id: 1, name: 'Project Nexus', description: 'Microservices architecture overhaul with automated scaling rules generated by AI.',
    status: 'Active', priority: 'High', category: 'Client', client: 'Acme Corp',
    ownerId: 1, startDate: '2026-05-01', endDate: '2026-09-15', progress: 78,
    teamIds: [1, 2, 5, 6, 3], icon: 'hub', color: 'primary', aiOptimized: true,
    tasksCount: 48, completedTasks: 37, updatesCount: 12,
  },
  {
    id: 2, name: 'Project Aegis', description: 'Implementing zero-trust security protocols across all internal dashboard interfaces.',
    status: 'Review', priority: 'Medium', category: 'Internal', client: null,
    ownerId: 2, startDate: '2026-06-01', endDate: '2026-10-30', progress: 45,
    teamIds: [2, 4], icon: 'security', color: 'tertiary', aiOptimized: false,
    tasksCount: 32, completedTasks: 14, updatesCount: 4,
  },
  {
    id: 3, name: 'Data Pipeline V2', description: 'Migrating legacy ETL processes to a real-time streaming architecture using Kafka and automated schema validation.',
    status: 'Planning', priority: 'Low', category: 'Internal', client: null,
    ownerId: 3, startDate: '2026-07-01', endDate: '2026-12-01', progress: 12,
    teamIds: [3, 5], icon: 'database', color: 'secondary', aiOptimized: false,
    tasksCount: 15, completedTasks: 2, updatesCount: 2,
  },
  {
    id: 4, name: 'LLM Fine-tuning', description: 'Training custom domain-specific models for automated customer support triage and sentiment analysis.',
    status: 'Active', priority: 'High', category: 'Internal', client: null,
    ownerId: 1, startDate: '2026-04-15', endDate: '2026-08-30', progress: 45,
    teamIds: [1, 6], icon: 'model_training', color: 'tertiary', aiOptimized: true,
    tasksCount: 28, completedTasks: 13, updatesCount: 8,
  },
  {
    id: 5, name: 'Legacy CRM Sync', description: 'Archived project. Replaced by the v3 API integration module completed last quarter.',
    status: 'Archived', priority: 'Low', category: 'Client', client: 'Globex',
    ownerId: 2, startDate: '2025-11-01', endDate: '2026-03-15', progress: 100,
    teamIds: [2, 3], icon: 'inventory_2', color: 'outline', aiOptimized: false,
    tasksCount: 40, completedTasks: 40, updatesCount: 0,
  },
  {
    id: 6, name: 'Q3 Marketing Campaign', description: 'Complete overhaul of the corporate marketing site focusing on generative AI integration.',
    status: 'Active', priority: 'High', category: 'Client', client: 'Acme Corp',
    ownerId: 2, startDate: '2026-06-15', endDate: '2026-09-30', progress: 68,
    teamIds: [2, 5, 6, 1, 3], icon: 'language', color: 'primary', aiOptimized: true,
    tasksCount: 36, completedTasks: 24, updatesCount: 15,
  },
]

export const SEED_TASKS = [
  // Backlog
  { id: 1, projectId: 1, title: 'Update component library geometry', status: 'Backlog', priority: 'Low', tag: 'Design', assigneeId: 5, dueDate: '2026-07-20', description: '' },
  { id: 2, projectId: 1, title: 'Implement lazy loading for 3D assets', status: 'Backlog', priority: 'Medium', tag: 'Frontend', assigneeId: null, dueDate: '2026-07-25', description: '' },
  { id: 3, projectId: 2, title: 'Define API rate-limiting rules', status: 'Backlog', priority: 'Medium', tag: 'Backend', assigneeId: 3, dueDate: '2026-07-28', description: '' },
  { id: 4, projectId: 1, title: 'Write integration tests for auth module', status: 'Backlog', priority: 'Medium', tag: 'QA', assigneeId: 6, dueDate: '2026-07-30', description: '' },
  // In Progress
  { id: 5, projectId: 1, title: 'Resolve API latency spikes in Auth flow', status: 'In Progress', priority: 'High', tag: 'AI Suggested', assigneeId: 5, dueDate: '2026-07-08', description: '', progress: 65, comments: 3 },
  { id: 6, projectId: 1, title: 'Migrate user session data to Redis cluster', status: 'In Progress', priority: 'Medium', tag: 'Backend', assigneeId: 3, dueDate: '2026-07-12', description: '' },
  // AI Review
  { id: 7, projectId: 1, title: 'Optimize vector search queries', status: 'AI Review', priority: 'Medium', tag: 'Evaluating', assigneeId: null, dueDate: '2026-07-15', description: 'Automated PR review in progress. Checking for O(n) complexities in the new search node implementation.', aiReview: true },
  // Completed
  { id: 8, projectId: 1, title: 'Patch OAuth vulnerability in staging', status: 'Completed', priority: 'High', tag: 'Security', assigneeId: 3, dueDate: '2026-07-01', description: '' },
  { id: 9, projectId: 2, title: 'Set up monitoring dashboards', status: 'Completed', priority: 'Medium', tag: 'DevOps', assigneeId: 1, dueDate: '2026-06-28', description: '' },
  { id: 10, projectId: 1, title: 'Database migration for user profiles', status: 'Completed', priority: 'Low', tag: 'Backend', assigneeId: 5, dueDate: '2026-06-25', description: '' },
  { id: 11, projectId: 6, title: 'Create login form', status: 'Completed', priority: 'High', tag: 'Frontend', assigneeId: 5, dueDate: '2026-06-20', description: '' },
  { id: 12, projectId: 6, title: 'Setup DB schema', status: 'In Progress', priority: 'High', tag: 'Backend', assigneeId: 3, dueDate: '2026-07-10', description: '' },
]

export const SEED_CHANNELS = [
  { id: 1, name: 'general', type: 'channel', unread: 0 },
  { id: 2, name: 'development', type: 'channel', unread: 1 },
  { id: 3, name: 'design-system', type: 'channel', unread: 0 },
  { id: 4, name: 'marketing', type: 'channel', unread: 0 },
]

export const SEED_MESSAGES = [
  {
    id: 1, channelId: 2, userId: 3, content: "Hey team, I've just pushed the initial commits for the new WebSocket integration. The latency looks much better now, hovering around 40ms on average. Take a look at PR #402 when you have a moment.",
    timestamp: '2026-07-01T10:42:00Z', reactions: [{ emoji: 'rocket_launch', count: 3 }], threadCount: 4,
  },
  {
    id: 2, channelId: 2, userId: 1, content: "Awesome work Marcus. I'll review it before the afternoon sync. Did you end up using the existing Redis cache for session state, or did we move to the new implementation?",
    timestamp: '2026-07-01T10:45:00Z', reactions: [], threadCount: 0, isCurrentUser: true,
  },
  {
    id: 3, channelId: 2, userId: null, isSystem: true,
    content: 'PR #402 has passed all CI/CD pipeline checks. Staging environment successfully deployed.',
    timestamp: '2026-07-01T11:00:00Z',
    embed: { title: 'Deploy Successful: staging-web-v2.1', subtitle: 'Duration: 4m 12s • Branch: feat/websocket-integration', status: 'success' },
  },
  {
    id: 4, channelId: 2, userId: 2, content: "Looking good. Let's make sure the design system components handle the new real-time updates smoothly without flickering.",
    timestamp: '2026-07-01T11:05:00Z', reactions: [], threadCount: 0,
  },
]

export const SEED_NOTIFICATIONS = [
  { id: 1, userId: 1, message: 'CI/CD Pipeline deployed successfully', type: 'success', read: false, createdAt: '2026-07-01T10:58:00Z' },
  { id: 2, userId: 1, message: 'Sarah Jenkins assigned you to "API Documentation"', type: 'task', read: false, createdAt: '2026-07-01T10:30:00Z' },
  { id: 3, userId: 1, message: 'AI detected 3 optimization opportunities', type: 'ai', read: true, createdAt: '2026-07-01T09:15:00Z' },
  { id: 4, userId: 1, message: 'Build failed in staging environment', type: 'error', read: true, createdAt: '2026-07-01T07:42:00Z' },
]

export const SEED_ACTIVITY = [
  { id: 1, type: 'deploy', title: 'CI/CD Pipeline', highlight: 'Success', description: 'Deployment #4092 to Production completed. All integration tests passed.', time: '2m ago', color: 'primary' },
  { id: 2, type: 'ai', title: 'AI Code Review', highlight: null, description: 'FlowForge AI suggested 3 optimizations for auth_service.ts.', time: '15m ago', color: 'tertiary', actionLabel: 'Review' },
  { id: 3, type: 'pr', title: 'Pull Request Merged', highlight: null, description: 'Sarah J. merged PR #882', time: '1h ago', color: 'outline', userId: 2 },
  { id: 4, type: 'error', title: 'Build Failed', highlight: null, description: 'Error in staging environment: Timeout connecting to DB cluster.', time: '3h ago', color: 'error' },
]

export const SEED_DEADLINES = [
  { id: 1, title: 'Q3 Security Audit', project: 'Project Aegis', due: 'Today', urgency: 'error' },
  { id: 2, title: 'Frontend Migration', project: 'Project Nexus', due: 'Tomorrow', urgency: 'primary' },
  { id: 3, title: 'API Documentation', project: 'Core Services', due: 'Jul 24', urgency: 'tertiary' },
]

export const SEED_AI_MESSAGES = [
  {
    id: 1, role: 'user',
    content: 'I need to set up a new project for the upcoming Q3 Marketing Campaign. Can you suggest a roadmap and identify potential bottlenecks?',
  },
  {
    id: 2, role: 'assistant',
    content: "I've analyzed the parameters for a standard Q3 Marketing Campaign. Here is a proposed roadmap and identified bottleneck risks.",
    roadmap: [
      { phase: 'Phase 1 (Weeks 1-2)', description: 'Market analysis and demographic targeting definition.', done: true },
      { phase: 'Phase 2 (Weeks 3-5)', description: 'Asset creation, copy drafting, and A/B testing setup.', done: true },
      { phase: 'Phase 3 (Weeks 6-10)', description: 'Execution, monitoring, and real-time bid adjustments.', done: false },
    ],
    bottlenecks: [
      { title: 'Asset Approval', description: 'Legal review often delays Phase 2 by 4-6 days historically.', severity: 'error' },
      { title: 'Cross-team Comm', description: 'Design and Copy teams operating in different sprint cycles.', severity: 'tertiary' },
    ],
  },
]
