-- FlowForge AI — Database Schema (H2 Compatible)
-- V1: Initial schema with all tables, indexes, and constraints

-- =============================================
-- USERS
-- =============================================
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL,
    email       VARCHAR(255)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role        VARCHAR(20)   NOT NULL DEFAULT 'DEVELOPER',
    avatar_url  VARCHAR(500),
    status      VARCHAR(20)   DEFAULT 'OFFLINE',
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);

-- =============================================
-- PROJECTS
-- =============================================
CREATE TABLE projects (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200)  NOT NULL,
    description  CLOB,
    owner_id     BIGINT        NOT NULL,
    start_date   DATE,
    end_date     DATE,
    status       VARCHAR(30)   NOT NULL DEFAULT 'ACTIVE',
    priority     VARCHAR(20)   DEFAULT 'MEDIUM',
    category     VARCHAR(30)   DEFAULT 'INTERNAL',
    client_name  VARCHAR(100),
    icon         VARCHAR(50)   DEFAULT 'folder_open',
    color        VARCHAR(30)   DEFAULT 'primary',
    progress     INT           DEFAULT 0,
    ai_optimized BOOLEAN       DEFAULT FALSE,
    created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_project_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE INDEX idx_projects_owner ON projects(owner_id);
CREATE INDEX idx_projects_status ON projects(status);
CREATE INDEX idx_projects_category ON projects(category);

-- =============================================
-- PROJECT MEMBERS (join table)
-- =============================================
CREATE TABLE project_members (
    project_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    joined_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (project_id, user_id),
    CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_pm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =============================================
-- TASKS
-- =============================================
CREATE TABLE tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT       NOT NULL,
    title        VARCHAR(300) NOT NULL,
    description  CLOB,
    status       VARCHAR(30)  NOT NULL DEFAULT 'BACKLOG',
    priority     VARCHAR(20)  DEFAULT 'MEDIUM',
    tag          VARCHAR(50),
    assignee_id  BIGINT,
    due_date     DATE,
    progress     INT          DEFAULT 0,
    ai_review    BOOLEAN      DEFAULT FALSE,
    sort_order   INT          DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_assignee FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_tasks_project ON tasks(project_id);
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_assignee ON tasks(assignee_id);

-- =============================================
-- COMMENTS
-- =============================================
CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT   NOT NULL,
    user_id    BIGINT   NOT NULL,
    content    CLOB     NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comment_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_comments_task ON comments(task_id);

-- =============================================
-- CHANNELS (Discord-like)
-- =============================================
CREATE TABLE channels (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    type       VARCHAR(20)  NOT NULL DEFAULT 'CHANNEL',
    topic      VARCHAR(300),
    project_id BIGINT,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_channel_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
);

-- =============================================
-- CHANNEL MEMBERS
-- =============================================
CREATE TABLE channel_members (
    channel_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    joined_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (channel_id, user_id),
    CONSTRAINT fk_cm_channel FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE,
    CONSTRAINT fk_cm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =============================================
-- MESSAGES
-- =============================================
CREATE TABLE messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id  BIGINT       NOT NULL,
    user_id     BIGINT,
    content     CLOB         NOT NULL,
    type        VARCHAR(20)  NOT NULL DEFAULT 'USER',
    embed_json  CLOB,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_msg_channel FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE,
    CONSTRAINT fk_msg_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_messages_channel ON messages(channel_id);

-- =============================================
-- MESSAGE REACTIONS
-- =============================================
CREATE TABLE message_reactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    emoji      VARCHAR(50) NOT NULL,
    created_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reaction_msg FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
    CONSTRAINT fk_reaction_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_reaction UNIQUE (message_id, user_id, emoji)
);

CREATE INDEX idx_reactions_message ON message_reactions(message_id);

-- =============================================
-- NOTIFICATIONS
-- =============================================
CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    message    VARCHAR(500) NOT NULL,
    type       VARCHAR(30)  DEFAULT 'INFO',
    is_read    BOOLEAN      DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_user ON notifications(user_id);

-- =============================================
-- AI CONVERSATIONS
-- =============================================
CREATE TABLE ai_conversations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    title      VARCHAR(200) DEFAULT 'New Conversation',
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_aichat_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =============================================
-- AI MESSAGES
-- =============================================
CREATE TABLE ai_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL,
    role            VARCHAR(20) NOT NULL,
    content         CLOB        NOT NULL,
    metadata_json   CLOB,
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_aimsg_conv FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_messages_conv ON ai_messages(conversation_id);
